name: release

permissions: write-all

on:
  workflow_dispatch:
    inputs:
      version:
        description: version
        required: true
        type: choice
        options:
          - major
          - minor
          - patch

jobs:
  release:
    uses: ci-space/workflows/.github/workflows/release-docker-github-action.yaml@f5cb72bdfd1ba4dde0732feae7870bcea78c18a7
    secrets: inherit
    with:
      version: ${{ github.event.inputs.version }}
      platforms: linux/amd64,linux/arm64
